import { createPublicClient, createWalletClient, custom, defineChain, formatEther, http, keccak256, parseAbi, type Address, type EIP1193Provider, type Hex } from 'viem';
declare const __REVIEW__: { config: { chainId:4663; deployer:Address; treasury:Address; friendFeeBps:8500; totalSupply:string }; verifiedAt:{blockNumber:string}; sourceHash:Hex; deploymentDataHash:Hex; catalogHash:Hex; unsignedTransaction:{data:Hex;from:Address;value:'0x0'}; quotes:{symbol:string;address:Address}[]; modules:{name:string;address:Address;state:number}[]; airlock:{address:Address}; validation?: {fullRouterSimulation?:string; deploymentDataHash?:Hex; catalogHash?:Hex} };
const review = __REVIEW__, chain = defineChain({id:4663,name:'Robinhood Chain',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:{default:{http:['https://rpc.mainnet.chain.robinhood.com']}},blockExplorers:{default:{name:'Robinhood Explorer',url:'https://robinhoodchain.blockscout.com'}}});
const client=createPublicClient({chain,transport:http(chain.rpcUrls.default.http[0],{timeout:15000,retryCount:0})});
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const status=(value:string)=>{$('status').textContent=value;};
const error=(cause:unknown)=>cause instanceof Error?cause.message:'The operation could not complete.';
const equal=(a:string,b:string)=>a.toLowerCase()===b.toLowerCase();
const abi=parseAbi(['function treasury() view returns(address)','function friendShares() view returns(uint96)','function treasuryShares() view returns(uint96)','function totalSupply() view returns(uint256)','function CHAIN_ID() view returns(uint256)','function quoteTokens() view returns(address[])','function getModuleState(address) view returns(uint8)']);
const storageKey=`rarepet:router-deployment:${keccak256(review.unsignedTransaction.data)}`;
let provider:EIP1193Provider|null=null, account:Address|null=null, gas:bigint|null=null, funded=false, busy=false, awaiting=false, submitted:Hex|null=null;
function update(){ $('deploy').toggleAttribute('disabled',busy||!account||!gas||!funded||!$<HTMLInputElement>('reviewed').checked||!!submitted||awaiting);$('estimate').toggleAttribute('disabled',busy||!account||!!submitted||awaiting);$('connect').toggleAttribute('disabled',busy||!!submitted||awaiting); }
function detail(label:string,value:string){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);$('details').append(row);}
detail('NETWORK','Robinhood Chain · 4663');detail('DEPLOYER / PAYS GAS',review.config.deployer);detail('RAREPET TREASURY / 10%',review.config.treasury);detail('TRADING FEE SPLIT','85% creator · 10% treasury · 5% Doppler');detail('PAIRS',`${review.quotes.length} verified quotes · WETH + ${review.quotes.length-1} stocks and ETFs`);const pairs=document.createElement('details'),summary=document.createElement('summary'),list=document.createElement('p');summary.textContent='VIEW ALL SUPPORTED PAIRS';list.textContent=review.quotes.map(q=>q.symbol).join(' · ');pairs.append(summary,list);$('details').append(pairs);detail('SUPPLY / ALLOCATION','1 billion per token · 100% pool allocation');detail('POLICY','Yourself: direct wallet. Rare Friend: canonical RF wallet, +1 Brain, one launch per 24h.');detail('SOURCE HASH',review.sourceHash);
$('validation').textContent='Local contract and adapter tests pass. Both complete routes — self and canonical RF wallet through the router into Doppler — passed read-only Robinhood mainnet simulations. The unsigned review records the configuration and gas estimate. These checks are not an audit.';
async function checkSigner(){if(!provider||!account)throw new Error('Connect the reviewed deployer wallet.');const ids=await provider.request({method:'eth_accounts'}) as string[];const id=await provider.request({method:'eth_chainId'});if(id!=='0x1237'||!ids[0]||!equal(ids[0],review.config.deployer)||!equal(account,review.config.deployer))throw new Error('Use the reviewed deployer on Robinhood Chain.');}
$('connect').onclick=async()=>{busy=true;update();try{const injected=(window as unknown as {ethereum?:EIP1193Provider}).ethereum;if(!injected)throw new Error('Open this local page in a browser with your wallet extension.');provider=injected;const accounts=await provider.request({method:'eth_requestAccounts'}) as Address[];if(!accounts[0]||!equal(accounts[0],review.config.deployer))throw new Error(`Select ${review.config.deployer} in your wallet.`);await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x1237'}]});account=accounts[0];gas=null;await checkSigner();status('Deployer connected. Check the current network fee.');}catch(cause){account=null;status(error(cause));}finally{busy=false;update();}};
async function checkFreshReview(){
  const response=await fetch('/review.json',{cache:'no-store'});
  if(!response.ok)throw new Error('The deployment review changed or is unavailable. Reload the verified local page.');
  const fresh=await response.json() as typeof review;
  if(fresh.deploymentDataHash!==review.deploymentDataHash||fresh.catalogHash!==review.catalogHash||fresh.unsignedTransaction.data!==review.unsignedTransaction.data||fresh.validation?.fullRouterSimulation!=='passed'||fresh.validation.deploymentDataHash!==review.deploymentDataHash||fresh.validation.catalogHash!==review.catalogHash)throw new Error('This page contains an outdated deployment or quote list. Reload the verified local page.');
}
async function estimate(){await checkFreshReview();await checkSigner();if(await client.getChainId()!==4663)throw new Error('RPC chain mismatch.');for(const module of review.modules){const state=await client.readContract({address:review.airlock.address,abi,functionName:'getModuleState',args:[module.address]});if(state!==module.state)throw new Error(`Doppler module changed: ${module.name}. Prepare a fresh review.`);}gas=await client.estimateGas({account:review.config.deployer,data:review.unsignedTransaction.data,value:0n});const [price,balance]=await Promise.all([client.getGasPrice(),client.getBalance({address:review.config.deployer})]);await checkSigner();funded=balance>=gas*price*120n/100n;$('estimate-value').textContent=`Estimated ${gas.toLocaleString()} gas · approximately ${formatEther(gas*price)} ETH at the current gas price. Wallet balance: ${formatEther(balance)} ETH.${funded?' Your wallet shows the final fee.':' Add ETH on Robinhood Chain, then check the fee again.'}`;}
$('estimate').onclick=async()=>{busy=true;gas=null;update();try{await estimate();status('Network fee checked. Review the details before deploying.');}catch(cause){gas=null;status(error(cause));}finally{busy=false;update();}};
async function confirm(hash:Hex){status(`Deployment submitted: ${hash}\nWaiting for confirmation…`);$('recheck').classList.remove('hidden');const receipt=await client.waitForTransactionReceipt({hash,timeout:120000,confirmations:1});const tx=await client.getTransaction({hash});if(!equal(tx.from,review.config.deployer)||tx.to!==null||tx.input!==review.unsignedTransaction.data||tx.value!==0n||tx.chainId!==4663||tx.blockHash!==receipt.blockHash)throw new Error('This transaction does not match the reviewed deployment. Inspect it before continuing.');if(receipt.status!=='success'||!receipt.contractAddress)throw new Error('Deployment reverted. Inspect the transaction before preparing another.');const address=receipt.contractAddress;const [treasury,friendShares,treasuryShares,supply,chainId,quotes,code]=await Promise.all([client.readContract({address,abi,functionName:'treasury'}),client.readContract({address,abi,functionName:'friendShares'}),client.readContract({address,abi,functionName:'treasuryShares'}),client.readContract({address,abi,functionName:'totalSupply'}),client.readContract({address,abi,functionName:'CHAIN_ID'}),client.readContract({address,abi,functionName:'quoteTokens'}),client.getCode({address})]);if(!code||code==='0x'||!equal(treasury,review.config.treasury)||friendShares!==850000000000000000n||treasuryShares!==100000000000000000n||supply!==BigInt(review.config.totalSupply)||chainId!==4663n||quotes.map(q=>q.toLowerCase()).join()!==review.quotes.map(q=>q.address.toLowerCase()).join())throw new Error('Deployed configuration did not match. Do not enable the app yet.');$('result').classList.remove('hidden');$('result').textContent=`Deployment confirmed and configuration checked.\nContract: ${address}\nTransaction: ${hash}\nSend this contract address to Codex to verify source and activate the launchpad.`;status('Deployment confirmed. No token has been launched.');$('recheck').classList.add('hidden');}
$('deploy').onclick=async()=>{if(busy||submitted||awaiting||!$<HTMLInputElement>('reviewed').checked)return;busy=true;update();try{await estimate();if(!funded)throw new Error('The deployer needs ETH on Robinhood Chain for the network fee.');await checkSigner();await checkFreshReview();const wallet=createWalletClient({account:review.config.deployer,chain,transport:custom(provider!)});status('Confirm contract deployment in your wallet.');localStorage.setItem(storageKey,JSON.stringify({status:'awaiting-wallet'}));awaiting=true;const hash=await wallet.sendTransaction({data:review.unsignedTransaction.data,value:0n,gas:gas!*120n/100n});submitted=hash;awaiting=false;status(`Deployment submitted: ${hash}`);$('recheck').classList.remove('hidden');try{localStorage.setItem(storageKey,JSON.stringify({status:'pending',hash}));}catch{/* The earlier awaiting-wallet record keeps reloads blocked. */}await confirm(hash);}catch(cause){const text=error(cause);if(!submitted&&/user rejected|user denied|rejected the request/i.test(text)){awaiting=false;localStorage.removeItem(storageKey);}status(text);if(awaiting&&!submitted)$('clear').classList.remove('hidden');}finally{busy=false;update();}};
$('recheck').onclick=async()=>{if(!submitted||busy)return;busy=true;update();try{await confirm(submitted);}catch(cause){status(error(cause));}finally{busy=false;update();}};
$<HTMLInputElement>('reviewed').onchange=update;
$('clear').onclick=()=>{if(busy||submitted||!awaiting)return;awaiting=false;localStorage.removeItem(storageKey);$('clear').classList.add('hidden');gas=null;status('Cancelled request cleared. Recheck the fee before continuing.');update();};
try{const raw=localStorage.getItem(storageKey);if(raw){const saved=JSON.parse(raw);if(saved.status==='pending'&&/^0x[0-9a-f]{64}$/i.test(saved.hash)){submitted=saved.hash;$('recheck').classList.remove('hidden');status(`Saved deployment transaction: ${submitted}. Recheck it before sending anything else.`);}else if(saved.status==='awaiting-wallet'){awaiting=true;$('clear').classList.remove('hidden');status('A previous wallet request did not return a transaction hash. Check your wallet activity before trying again. Only clear this if you cancelled it and no deployment was submitted.');}else{throw new Error('Unrecognized deployment record.');}}}catch{status('Saved deployment state could not be read. Check your wallet activity before proceeding.');awaiting=true;$('clear').classList.remove('hidden');}
update();
