import { PetBrand } from './art';
import './docs.css';

export type DocsProps = { petGraceHours?: number };
const sections = [
  ['start', 'Getting started'], ['modes', 'Preview & My Wallet'], ['friends', 'Your Rare Friend'],
  ['care', 'Care & cooldowns'], ['traits', 'Traits'], ['streaks', 'Streaks & rarity'], ['onchain', 'What is live'],
] as const;
const careActions = [
  { name: 'Pet', timing: 'Every 24 hours', gain: '+1 Kinship', detail: 'Give your Friend a little love. Each successful pet starts the next 24-hour cooldown and advances an unbroken care streak.' },
  { name: 'Feed', timing: 'Every 4 hours', gain: '+1 Strength · +5 Stamina', detail: 'Serve a meal when Feed is ready. Its own four-hour timer starts after each meal.' },
  { name: 'Play', timing: '3 completions per rolling 24 hours', gain: '+10 Experience', detail: 'Open Rare Rush with your selected Friend: run, ride suction shafts, free-fall and follow surprise direction changes. Finish a run to earn Experience. Each rewarded completion uses one slot, which returns 24 hours after that completion.' },
  { name: 'Launch', timing: 'Every 24 hours · coming soon', gain: 'Brain · coming soon', detail: 'Connect your Friend to Rare Launchpad launches when this feature arrives. Launch is currently unavailable.' },
  { name: 'Poop', timing: 'Every 4 hours', gain: '+1 Health', detail: 'A healthy little break. Its four-hour timer runs independently of Feed, Pet and Play.' },
];

/** The parent supplies the confirmed grace period so the guide matches the care model. */
export function Docs({ petGraceHours = 24 }: DocsProps) {
  const petDeadlineHours = 24 + petGraceHours;
  return <div className="rarepet-app docs-app">
    <a className="docs-skip" href="#docs-main">Skip to documentation</a>
    <div className="site-header-shell"><header className="site-header">
      <a className="site-logo" href="/" aria-label="RarePet home"><PetBrand/></a>
      <nav aria-label="Main navigation"><a className="docs-nav-link" href="/">HOME</a><a className="docs-nav-link" href="/docs/" aria-current="page">DOCS</a></nav>
    </header></div>
    <main className="docs-main" id="docs-main">
      <div className="docs-hero"><div><span className="docs-eyebrow">RAREPET / DOCS</span><h1>CARE. PLAY.<br/><span>STAY RARE.</span></h1><p>Your Rare Friend, a daily ritual. Learn the care loop, try it in Preview, and bring your own Friend with My Wallet.</p></div><a className="docs-open" href="/">OPEN RAREPET <span aria-hidden="true">↗</span></a></div>
      <div className="docs-layout">
        <aside className="docs-index"><span className="docs-eyebrow">IN THIS GUIDE</span><nav aria-label="Documentation contents">{sections.map(([id, title], i) => <a key={id} href={`#${id}`}><span>{String(i + 1).padStart(2, '0')}</span>{title}</a>)}</nav></aside>
        <article className="docs-content">
          <section id="start"><span className="docs-section-number">01 / START HERE</span><h2>A little care. Every day.</h2><p>RarePet gives your Genesis or Generations Rare Friend a place to live, play and grow. Choose a Friend, pick an island and return when its care actions are ready.</p><ol className="docs-steps"><li><b>Choose your mode.</b> Preview works without a wallet. My Wallet lets you select a Friend you own.</li><li><b>Make it yours.</b> Choose an island. Genesis Friends can try any of the 36 Rare Rush bodies.</li><li><b>Care and come back.</b> Pet, Feed and Poop have separate cooldowns. Play earns preview Experience after a completed Rare Rush run.</li></ol></section>
          <section id="modes"><span className="docs-section-number">02 / TWO WAYS IN</span><h2>Preview & My Wallet</h2><div className="docs-mode-grid"><div><h3>PREVIEW</h3><p>Try three Genesis and three Generations samples without connecting a wallet, signing anything or paying a network fee.</p><p>Care is saved on this device, separately for each Friend. Reset Preview clears only the selected sample’s care. Preview points have no onchain value.</p></div><div><h3>MY WALLET</h3><p>Connect a compatible browser wallet on Robinhood Chain and choose a Genesis or Generations Friend you own. RarePet checks current ownership before selection.</p><p>Wallet ownership is live. Onchain care is awaiting deployment, so owned Friends do not receive simulated preview points.</p></div></div><p>You can switch back to Preview while your wallet remains connected. Your preview care stays separate from your owned Friend.</p></section>
          <section id="friends"><span className="docs-section-number">03 / SAME FRIEND, NEW HOME</span><h2>Your Rare Friend</h2><p>Genesis keeps its original portrait and uses the same 36 cosmetic bodies as Rare Rush. Change Body picks a different body and carries it into the embedded game. Generations uses its original Rare Friends artwork.</p><p>Choose from 16 islands: six original Rare Friends worlds, the five Classic floors, and five Floating styles. Classic and Floating each offer Meadow, Moon, Arcade, Beach and Rare. Background islands can mix everything, mix one collection, match your main island or use a specific design. Your island, background, Genesis body and last preview Friend are remembered on this device.</p><p className="docs-note">Bodies and islands are cosmetic. They do not change NFT artwork or metadata, game physics, care rewards or eligibility. RarePet care traits are separate from the original collection traits.</p><p>My Wallet supports Genesis and Generations selection. Rare Rush accepts Genesis and hardwired Generations Friends; a Generations Friend that is not eligible for Rush can still be selected for care.</p></section>
          <section id="care"><span className="docs-section-number">04 / YOUR OWN TIMERS</span><h2>Care & cooldowns</h2><p>Each action follows its own timer. There is no shared midnight reset. The dashboard shows when the next action or Play slot becomes available.</p><div className="docs-actions">{careActions.map((action, i) => <div className="docs-action" key={action.name}><div className="docs-action-heading"><span>{String(i + 1).padStart(2, '0')}</span><h3>{action.name}</h3><b>{action.timing}</b></div><p>{action.detail}</p><span className="docs-gain">{action.gain}</span></div>)}</div><p className="docs-note">Opening Rare Rush or leaving an unfinished run earns no Experience. Only a completed run grants preview XP. A fourth reward becomes available when the oldest of your three active completion slots reaches 24 hours.</p></section>
          <section id="traits"><span className="docs-section-number">05 / A LITTLE GROWTH</span><h2>What the traits mean</h2><dl className="docs-traits"><div><dt>Kinship</dt><dd>Your bond. Pet to increase it; a missed care window reduces it.</dd></div><div><dt>Strength</dt><dd>Grows with each meal.</dd></div><div><dt>Stamina</dt><dd>Grows by five per meal. It currently accumulates as a care trait and is not spent to enter Rare Rush.</dd></div><div><dt>Experience</dt><dd>Grows by ten after a completed, eligible Rare Rush preview run.</dd></div><div><dt>Brain</dt><dd>Reserved for Rare Launchpad. Launch and Brain rewards are coming soon.</dd></div><div><dt>Health</dt><dd>Grows with each Poop action.</dd></div><div><dt>Rarity</dt><dd>Your RarePet streak score. Each seven consecutive care cycles adds one point; this does not change the NFT’s original rarity.</dd></div></dl></section>
          <section id="streaks"><span className="docs-section-number">06 / KEEP THE BOND</span><h2>Streaks & rarity</h2><p>Your first Pet starts a streak of one. Pet unlocks 24 hours after your last successful Pet.{petGraceHours > 0 ? ` You then have a ${petGraceHours}-hour grace window to pet again and keep the streak.` : ' Pet again when it unlocks to keep the streak.'}</p><div className="docs-timeline"><div><span>LAST PET</span><b>0h</b><small>Cooldown starts</small></div><div><span>READY AGAIN</span><b>24h</b><small>Next Pet unlocks</small></div><div><span>BOND DEADLINE</span><b>{petDeadlineHours}h</b><small>Since your last Pet</small></div></div><p>Pet on or before the bond deadline to continue the streak. Missing it resets the streak and its Rarity, and loses one Kinship. Each additional missed 24-hour period loses another Kinship, down to zero. Your next Pet begins a new streak.</p><p>Every seven consecutive care cycles adds one Rarity. Feed, Play and Poop do not refresh the Pet deadline.</p></section>
          <section id="onchain"><span className="docs-section-number">07 / CURRENT STATUS</span><h2>What is live</h2><div className="docs-status"><span className="docs-status-mark" aria-hidden="true">✦</span><div><h3>Preview care. Real NFT ownership.</h3><p>Preview care and Rare Rush are available now. My Wallet verifies your real Rare Friends on Robinhood Chain. The RarePet care contract has not been deployed yet.</p></div></div><p>Once live care is enabled, Pet, Feed and Poop will ask for a wallet transaction. Connecting a wallet by itself does not perform a care action. RarePet does not take custody of your NFT.</p><p>Live Experience needs a verified game-completion service. That service is not connected yet, so playing with an owned Friend does not currently grant onchain XP. Launch is also coming soon.</p><a className="docs-return" href="/">BACK TO YOUR RAREPET <span aria-hidden="true">↗</span></a></section>
        </article>
      </div>
      <footer className="docs-footer"><div className="docs-signature"><span>RARE PET BY XIBOT</span><small>ROBINHOOD CHAIN</small></div><p>A little pet, a little play, a lot of rare.</p><a href="https://rarefriends.com" target="_blank" rel="noreferrer">RARE FRIENDS <span aria-hidden="true">↗</span></a></footer>
      <p className="credits"><a href="/credits.txt" target="_blank" rel="noreferrer">Rare Friends artwork · Built with FriendSDK</a></p>
    </main>
  </div>;
}
